name: Generate Snake

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: true

      - name: Generate Snake
        uses: Platane/snk@v2
        with:
          args: "--width 600 --height 200"

      - name: Commit and Push
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add snake.svg
          git commit -m "Updated snake animation" || echo "No changes to commit"
          git push
