name: Generate Snake

on:
  schedule:
    - cron: '0 * * * *'  # Runs every hour
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          persist-credentials: true

      - name: Generate Snake Contribution Grid
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: dist/snake.svg  # Saves file in "dist/" folder

      - name: Commit and Push Generated Snake
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add dist/snake.svg
          git commit -m "Updated snake animation" || echo "No changes to commit"
          git push
  
